FROM ros:noetic

# Set up ROS environment
WORKDIR /ros_ws
RUN mkdir -p /ros_ws/src

# Copy ROS packages
COPY ./ros_ws/src /ros_ws/src

# Build ROS workspace
RUN /bin/bash -c '. /opt/ros/noetic/setup.bash && \
    catkin_make && \
    echo "source /ros_ws/devel/setup.bash" >> ~/.bashrc'

# Expose ROS master port
EXPOSE 11311

# Launch ROS master
CMD ["roscore"] 